version: '3.9'

services:
  exchange_service_db:
    build:
      dockerfile: Dockerfile
      context: db
    container_name: exchange_service_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - exchange_service_db:/var/lib/postgresql/data
    networks:
      - crypto-service

  exchange_service:
    build:
      dockerfile: Dockerfile
    container_name: exchange_service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - exchange_service_db
    networks:
      - crypto-service

volumes:
  exchange_service_db:

networks:
  crypto-service:
    driver: bridge