spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/exchange_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: db/liquibase-changelog.yaml
    enabled: ${LIQUIBASE_ENABLED:true}